### ISSUE TITLE
生成的时候报错了 为啥

### ISSUE THREAD

**Issue by coolbabay** [gloxec/CrossC2#19]
./genCrossC2.Linux 192.168.106.156 443 null null Linux x86 ./cross-test

read keys error
Exception in thread "main" java.lang.NoClassDefFoundError: common/CommonUtils
        at genKey.BeaconKey.main(BeaconKey.java:52)
Caused by: java.lang.ClassNotFoundException: common.CommonUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
*[error] : read key error

**Comment by coolbabay** [comment]
嗷嗷 原来把文件单独拿出来放在cs根目录下
