### ISSUE TITLE
genCrossC2.MacOS 执行中报错

### ISSUE THREAD

**Issue by pyking** [gloxec/CrossC2#9]
已经把server下的key复制到了本地目录，并给与了执行权限，还是在运行时候报了个错

报错内容：
Exception in thread "main" java.lang.NoClassDefFoundError: common/CommonUtils
	at genKey.BeaconKey.main(BeaconKey.java:52)
Caused by: java.lang.ClassNotFoundException: common.CommonUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
*[error] : read key error

**Comment by gloxec** [comment]
参考README中详细使用方法

> 拷贝 CrossC2.cna 与 genCrossC2 文件到CobaltStrike 根目录 下
